language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 5.0.102
branches:
  only:
    - master
#    - develop
script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: involuted-disk-341923-69a1e0e5fa21.json
    project: involuted-disk-341923
    version: service-demo
    default: true
    on:
        all_branches: true